### ISSUE TITLE
How to handle statusCode ?

### ISSUE THREAD

**Issue by tranvanphay** [Mindinventory/flutter-retrofit#2]
Hello, 
This is great example, but I cannot handle error status code, it just run well when statusCode = 200. I have try to add this code and it run well on all statusCode, but it is auto generate file. Did you know, how to handle it ? 
![image](https://user-images.githubusercontent.com/42576241/123355299-9a422d80-d58f-11eb-8978-3d42908295b0.png)

**Comment by semiosisgit-ash** [comment]
Any update ??

**Comment by hetashree** [comment]
Hii @tranvanphay & @semiosisgit-ash

I have added the failure state in FutureBuilder _buildBody function in main.dart file. 
After any single change in that we have to fire the  below commend in our android studio terminal.
```
flutter packages pub run build_runner build --delete-conflicting-outputs
```

As we have auto generated file and it will reflect only after fire this command. 
let me share that code here. 
```
 FutureBuilder<ResponseData> _buildBody(BuildContext context) {
    final client = ApiClient(Dio(BaseOptions(contentType: "application/json")));
    return FutureBuilder<ResponseData>(
      future: client.getUsers(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          final ResponseData posts = snapshot.data;
          if (posts != null) {
            return _buildListView(context, posts);
          } else {
            return Center(
              child: Container(
                child: Text('No Data'),
              ),
            );
          }
        } else if (snapshot.connectionState == ConnectionState.none) {
          return Center(
            child: Container(
              child: Text('No Data'),
            ),
          );
        } else {
          return Center(
            child: CircularProgressIndicator(),
          );
        }
      },
    );
  }
```
Please let me know if any regarding to this. 
Thanks.

**Comment by deep-mindinventory** [comment]
Closing issue due to no response.
