### ISSUE TITLE
AppRepository utility ?

### ISSUE THREAD

**Issue by Gobmichet** [Mindinventory/flutter-retrofit#5]
Hi,

Can you please explain the utility of "AppRepository" class in the project ?
Since i couldn't figure it out, i just deleted it and everything still work fine...
So what's the point ?

Thanks in advance,

**Comment by deep-mindinventory** [comment]
Hi @Gobmichet 
Normally repository class is responsible for the operation of the remote server or local database. It is part of the architecture. 
It is not necessary to create unless you expect its use in architecture like Bloc-based architecture in a flutter. This is an example of a repository which can be used in actual project  ex. AuthRepository, ProductRepository etc.
